version: 0.1

environment_variables:
    plaintext:
        ENDPOINT: "example.com"

phases:
    install:
        commands:
            - npm install
    pre_build:
        commands:
            - npm test
    build:
        commands:
            - docker build -t deleteme ./
#    post_build:
#        commands:
#            - docker push deleteme ecr
artifacts:
    files:
        - package.json
        - index.js
    discard-paths: yes
    base-directory: /var/www/

